---

- name: Check network device OS
  assert:
    that: >
      ansible_network_os == 'nxos' or
      ansible_network_os == 'ios' or
      ansible_network_os == 'junos'

- name: NXOS configure motd 
  nxos_banner:
    banner: motd
    text: "{{ motd_string }}"
    state: present
  when: >
    ansible_network_os == 'nxos'
  tags: 
    - motd_config